In [1]:
import numpy as np
import torch
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.7.1+cpu


#introduction to tensors


In [2]:
#scalar
scalar = torch.tensor(7)
scalar


tensor(7)

pytorch tensors are created using torch.Tensors() => read assignment

In [3]:
scalar.ndim

0

In [4]:
#get tensor back as python int
scalar.item()

7

In [5]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
#matrix
MATRIX = torch.tensor([[2,3],[6,9]])
MATRIX

tensor([[2, 3],
        [6, 9]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
#tensor
TENSOR = torch.tensor([[[[5,5,5],[5,5,5]], [[6,6,5], [6,6,5]], [[1,1,1], [1,1,1]]]])
TENSOR

tensor([[[[5, 5, 5],
          [5, 5, 5]],

         [[6, 6, 5],
          [6, 6, 5]],

         [[1, 1, 1],
          [1, 1, 1]]]])

In [12]:
TENSOR.ndim

4

In [13]:
TENSOR.shape

torch.Size([1, 3, 2, 3])

1 batch, 3 matrices, 2 rows, 3 columns. => 4D tensor.


---



###Random tensor


- why random tensors?
- cus the way many NN kearns => start of tensors of rands, adjust em th represent data

steps?

`start w rand => look @data => update rand => look @data => update rand`

t2: ==> read randoms from documentation>>>

In [14]:
#random tensors => shape (3,4)

random_ten = torch.rand(3,4)
random_ten

tensor([[0.5296, 0.0805, 0.0525, 0.1052],
        [0.2052, 0.1716, 0.2288, 0.4170],
        [0.4376, 0.8735, 0.7321, 0.9864]])

In [15]:
random_ten.ndim

2

In [16]:
ran_ten = torch.rand(10,10)
ran_ten

tensor([[0.7684, 0.4564, 0.8761, 0.5513, 0.4093, 0.9943, 0.3301, 0.4018, 0.7527,
         0.6644],
        [0.6310, 0.4707, 0.3950, 0.2472, 0.8013, 0.1111, 0.8026, 0.3912, 0.6141,
         0.3975],
        [0.9726, 0.1932, 0.9792, 0.7268, 0.3242, 0.7529, 0.3430, 0.5894, 0.1700,
         0.8594],
        [0.7831, 0.9335, 0.1758, 0.0377, 0.7145, 0.8127, 0.8792, 0.6861, 0.0261,
         0.3922],
        [0.9587, 0.7605, 0.3676, 0.3856, 0.9598, 0.9806, 0.5540, 0.2949, 0.9900,
         0.9588],
        [0.1544, 0.7748, 0.0486, 0.2056, 0.5264, 0.1344, 0.2934, 0.0362, 0.9608,
         0.3282],
        [0.5749, 0.6678, 0.9777, 0.2019, 0.4470, 0.4054, 0.8132, 0.8745, 0.2080,
         0.8868],
        [0.0821, 0.4382, 0.4401, 0.6651, 0.8749, 0.0676, 0.9582, 0.8224, 0.6343,
         0.8011],
        [0.5337, 0.0197, 0.7985, 0.1808, 0.8834, 0.7629, 0.5529, 0.8108, 0.7012,
         0.7973],
        [0.6932, 0.4194, 0.3438, 0.7289, 0.9153, 0.8325, 0.4250, 0.4106, 0.3318,
         0.0553]])

In [17]:
ran_ten.ndim

2

In [18]:
ran_tenn = torch.rand(3,3,3)
ran_tenn
ran_tenn.ndim

3

### Random tensor similar shape as image tensor:

In [19]:
rand_img_tens = torch.rand(size=(244,244,3))
#heigt, width, color channel(rgb)
rand_img_tens.shape, rand_img_tens.ndim

(torch.Size([244, 244, 3]), 3)

In [20]:
rand_img_tens

tensor([[[0.9109, 0.1024, 0.5079],
         [0.8630, 0.4743, 0.6020],
         [0.8515, 0.4294, 0.9699],
         ...,
         [0.4423, 0.5140, 0.9269],
         [0.8861, 0.9366, 0.3107],
         [0.5222, 0.2230, 0.0912]],

        [[0.4290, 0.7388, 0.1044],
         [0.6006, 0.3462, 0.9772],
         [0.8380, 0.6416, 0.8803],
         ...,
         [0.5836, 0.6168, 0.2170],
         [0.2009, 0.8957, 0.4226],
         [0.5178, 0.8376, 0.9995]],

        [[0.1481, 0.1370, 0.9106],
         [0.9318, 0.0068, 0.0997],
         [0.6246, 0.3446, 0.0168],
         ...,
         [0.8293, 0.9592, 0.5239],
         [0.9625, 0.3471, 0.2902],
         [0.8733, 0.3484, 0.5653]],

        ...,

        [[0.3796, 0.0241, 0.5106],
         [0.9622, 0.4643, 0.6240],
         [0.1993, 0.7758, 0.3852],
         ...,
         [0.3570, 0.4773, 0.1986],
         [0.1220, 0.7337, 0.0591],
         [0.0572, 0.4500, 0.3834]],

        [[0.1605, 0.5377, 0.9626],
         [0.7854, 0.4877, 0.6506],
         [0.

Zeros and Ones


In [21]:
#tensor of zeros
zero = torch.zeros(3,4)
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
zero * random_ten

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
#tensor of ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [24]:
ones.dtype

torch.float32

In [25]:
random_ten.dtype

torch.float32

### creating range of tensors & tensors alike

In [26]:
#using torch.range/arange
one_ten = torch.arange(0,10,2)
one_ten

tensor([0, 2, 4, 6, 8])

In [27]:
#tensor like
ten_zero = torch.zeros_like(one_ten)
ten_zero

tensor([0, 0, 0, 0, 0])

In [28]:
ten_shape = torch.arange(1,100,5)
#ten_shape
ten1_shape = torch.ones_like(ten_shape)
ten2_shape = torch.zeros_like(ten_shape)
rten = torch.rand(1,20)
ten1_shape + ten2_shape + rten

tensor([[1.4607, 1.7411, 1.5373, 1.5159, 1.8342, 1.0022, 1.9489, 1.4445, 1.0423,
         1.6130, 1.9687, 1.4364, 1.8394, 1.1160, 1.0711, 1.4397, 1.7246, 1.2093,
         1.2812, 1.4393]])

###Tensor datatypes

In [29]:
#float 32 tensor
f32_ten = torch.tensor([3.0,6.0,9.0], #anything else is auto assigned, no need t add manually.
                       dtype=None,
                       device = None, #dev ur tensor on + track gradient w this op
                       requires_grad = False) #
f32_ten

tensor([3., 6., 9.])

In [30]:
f32_ten.dtype

torch.float32

### problems with tensors:
1. not right data type => f16 in f32
2. not right shape => matrix mult
3. not right device => device ="cpu" / "cuda" -> operations on tensors on diff devices.

In [31]:
f16_Ten = f32_ten.type(torch.float16)
f16_Ten #conversion to not run into "not right shape" problem.

tensor([3., 6., 9.], dtype=torch.float16)

In [32]:
f16_Ten * f32_ten

tensor([ 9., 36., 81.])

In [33]:
int32 = torch.tensor([3,6,9], dtype = torch.int32)
int32


tensor([3, 6, 9], dtype=torch.int32)

In [34]:
int32 * f16_Ten

tensor([ 9., 36., 81.], dtype=torch.float16)

### getting info from tensors

- data type check => to get data type: use tensor.dtype
- shape check => tensor.shape
- device => tensor.device


In [35]:
some = torch.rand(3,4)
some

tensor([[0.0914, 0.9410, 0.1424, 0.8009],
        [0.4792, 0.1743, 0.8004, 0.5843],
        [0.5090, 0.0293, 0.3775, 0.6541]])

In [36]:
#fetch details
print(some)
print(f"data type: {some.dtype}")
print(some.size())
print(some.shape)
print(some.device)
some = some.to('cpu')
print(some.device)


tensor([[0.0914, 0.9410, 0.1424, 0.8009],
        [0.4792, 0.1743, 0.8004, 0.5843],
        [0.5090, 0.0293, 0.3775, 0.6541]])
data type: torch.float32
torch.Size([3, 4])
torch.Size([3, 4])
cpu
cpu


### manipulating tensors
- addition
- subtraction
* multiplication
- division
- MATRIX MULTIP

In [37]:
# addition
tensor = torch.tensor([1,2,3])
#tensor + 10
#tensor *10
#tensor -10
#tensor/10


In [38]:
#there's built-in functions:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [39]:
#MATRIX MUL
#1. element wiste
print(tensor * tensor)


tensor([1, 4, 9])


In [40]:
#2. dot product
%time

torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 24.3 μs


tensor(14)

In [41]:
#MATRIX MUL by hand
#1*1 + 2*2 + 3*3

%time
sum =0
for i in tensor:
  sum += i*i

sum

CPU times: total: 0 ns
Wall time: 27.4 μs


tensor(14)

### one of the most common errors in matrix multiplication => shape error
-- inner dimensions MUST match

In [42]:
# shapes for mat mul
tensor_a = torch.tensor([[1,2], [3,4],[5,6]])
tensor_b = torch.tensor([[1,2], [3,4],[5,6]])

#torch.mm(tensor_a, tensor_b) #alias for matmul
#RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

### to fix the shape issues => **transpose**
transpose -> switches axes or dimensions of a given tensor


In [43]:
tensor_b.T, tensor_b.T.shape
#makes a copy, doesn't change the original tensor_b

(tensor([[1, 3, 5],
         [2, 4, 6]]),
 torch.Size([2, 3]))

In [44]:
#works when b is transposed
torch.mm(tensor_a, tensor_b.T)

tensor([[ 5, 11, 17],
        [11, 25, 39],
        [17, 39, 61]])

## Tensor aggregation


In [45]:
x = torch.arange(1,100,10)
x


tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [46]:
torch.min(x) , x.min()

(tensor(1), tensor(1))

In [47]:
torch.max(x),  x.max()

(tensor(91), tensor(91))

In [48]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()
#RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long
#tensor NOT THE RIGHT DATA TYPE ==> HIDDEN

(tensor(46.), tensor(46.))

In [49]:
x.dtype
#long = int

torch.int64

In [50]:
torch.sum(x), x.sum()

(tensor(460), tensor(460))

### positional min, max?
- finding the position in tensor that has the min val with argmin, returns index position of target tensor when min val occures


In [51]:
x.argmin() #for the min val's INDEX VALUE

tensor(0)

In [52]:
x[0]

tensor(1)

In [53]:
x.argmax()

tensor(9)

In [54]:
x[9]

tensor(91)

## reshaping, stacking, squeezing, unsqueezing

- reshaping: -shape mismatch in MATRIX- => reshapes tensor in defined shape
- view: return view of a tensor in some shape, but just a copy not the original one
- stacking: combine multi tensors on top -vstack- or side by side -hstack- 
- squeeze: removes all `1` dimensions from tensor
- unsqueeze: adds `1` dimension to a target tensor
- permute: return view of input with dimensions (swapped) in a certain way

In [ ]:
x = torch.arange(1., 10.)
x, x.shape 

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
#reshape: extra dim => gotta be compatible with original size
x_reshaped = x.reshape(1,9)
#(2,9) => 18 elements, 9/dim
#(9,1) => 1 element, 9 dim 
x_reshaped, x_reshaped.shape 

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [62]:
#view => shares memo with ORIGINAL tensor
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [63]:
#changing z => changes x
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
#stack => v:0, h:1 
x_stack = torch.stack([x,x,x,x], dim=0)
x_stack

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [72]:
#squeeze
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [77]:
x_squeezed = x_reshaped.squeeze()
x_squeezed
#shape=[9] => removes all 1 dimensions!

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [81]:
#unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=1) #dim=0 aka adding the extra dimension to the zeroth index of the size/tensor or adding new dimension in new index => dim=1
x_unsqueezed

tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [84]:
#permute => rearrange dim of target tensor in specified order
#try image example:
x_original = torch.rand(size =(244,244,3) )

#return view(shares original memo) => view that changes the SIZE DIM themselves
x_perm = x_original.permute(2,0,1)

print(f"prev shape: {x_original.shape}")
print(f"new shape: {x_perm.shape}")
#same data, different POV, share same memory even though diff shapes

prev shape: torch.Size([244, 244, 3])
new shape: torch.Size([3, 244, 244])


## indexing 