<a href="https://colab.research.google.com/github/lillfirefly/PyTorch/blob/main/colab2hrs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import torch
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

ModuleNotFoundError: No module named 'numpy'

#introduction to tensors


In [ ]:
#scalar
scalar = torch.tensor(7)
scalar


tensor(7)

pytorch tensors are created using torch.Tensors() => read assignment

In [ ]:
scalar.ndim

0

In [ ]:
#get tensor back as python int
scalar.item()

7

In [ ]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#matrix
MATRIX = torch.tensor([[2,3],[6,9]])
MATRIX

tensor([[2, 3],
        [6, 9]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#tensor
TENSOR = torch.tensor([[[[5,5,5],[5,5,5]], [[6,6,5], [6,6,5]], [[1,1,1], [1,1,1]]]])
TENSOR

tensor([[[[5, 5, 5],
          [5, 5, 5]],

         [[6, 6, 5],
          [6, 6, 5]],

         [[1, 1, 1],
          [1, 1, 1]]]])

In [ ]:
TENSOR.ndim

4

In [ ]:
TENSOR.shape

torch.Size([1, 3, 2, 3])

1 batch, 3 matrices, 2 rows, 3 columns. => 4D tensor.


---



###Random tensor


- why random tensors?
- cus the way many NN kearns => start of tensors of rands, adjust em th represent data

steps?

`start w rand => look @data => update rand => look @data => update rand`

t2: ==> read randoms from documentation>>>

In [ ]:
#random tensors => shape (3,4)

random_ten = torch.rand(3,4)
random_ten

tensor([[0.6753, 0.3409, 0.6104, 0.2198],
        [0.1061, 0.5329, 0.9720, 0.4717],
        [0.8349, 0.8160, 0.7757, 0.8984]])

In [ ]:
random_ten.ndim

2

In [ ]:
ran_ten = torch.rand(10,10)
ran_ten

tensor([[0.5031, 0.7512, 0.4637, 0.8829, 0.5628, 0.3021, 0.2606, 0.4792, 0.6143,
         0.2470],
        [0.2946, 0.0987, 0.3034, 0.7343, 0.2018, 0.5991, 0.8087, 0.8384, 0.9464,
         0.2233],
        [0.2197, 0.0482, 0.1554, 0.9353, 0.3337, 0.8112, 0.1441, 0.5604, 0.6472,
         0.1572],
        [0.3621, 0.7558, 0.0661, 0.7174, 0.7543, 0.1129, 0.0849, 0.0897, 0.1935,
         0.1430],
        [0.6156, 0.6200, 0.2007, 0.9066, 0.0701, 0.0105, 0.1317, 0.1702, 0.6254,
         0.2155],
        [0.0730, 0.7814, 0.6943, 0.4313, 0.6177, 0.3477, 0.6366, 0.8420, 0.9294,
         0.4490],
        [0.2769, 0.0251, 0.5247, 0.7140, 0.7242, 0.9517, 0.9996, 0.8436, 0.5716,
         0.9816],
        [0.1418, 0.3009, 0.1327, 0.8854, 0.5461, 0.4946, 0.6829, 0.6200, 0.4554,
         0.6464],
        [0.2196, 0.0294, 0.7486, 0.7586, 0.1330, 0.7858, 0.4656, 0.5682, 0.1992,
         0.6365],
        [0.7194, 0.4930, 0.0472, 0.9269, 0.6352, 0.6472, 0.3404, 0.0790, 0.8131,
         0.9922]])

In [ ]:
ran_ten.ndim

2

In [ ]:
ran_tenn = torch.rand(3,3,3)
ran_tenn
ran_tenn.ndim

3

### Random tensor similar shape as image tensor:

In [ ]:
rand_img_tens = torch.rand(size=(244,244,3))
#heigt, width, color channel(rgb)
rand_img_tens.shape, rand_img_tens.ndim

(torch.Size([244, 244, 3]), 3)

In [ ]:
rand_img_tens

tensor([[[0.4767, 0.7293, 0.5082],
         [0.3431, 0.9855, 0.4086],
         [0.0793, 0.3063, 0.4514],
         ...,
         [0.9681, 0.5890, 0.8253],
         [0.0531, 0.1784, 0.3071],
         [0.2647, 0.0926, 0.5458]],

        [[0.9035, 0.4913, 0.4406],
         [0.1012, 0.9260, 0.6348],
         [0.1210, 0.7605, 0.5247],
         ...,
         [0.2785, 0.8567, 0.4592],
         [0.9167, 0.4419, 0.9577],
         [0.4201, 0.2899, 0.3557]],

        [[0.8119, 0.9226, 0.3812],
         [0.8646, 0.2822, 0.0559],
         [0.9103, 0.9750, 0.3308],
         ...,
         [0.2482, 0.7844, 0.9868],
         [0.6551, 0.4107, 0.1634],
         [0.4338, 0.2425, 0.7997]],

        ...,

        [[0.2878, 0.6691, 0.2409],
         [0.8348, 0.7157, 0.5017],
         [0.0795, 0.3264, 0.0105],
         ...,
         [0.8524, 0.6028, 0.7772],
         [0.4484, 0.6395, 0.4089],
         [0.3872, 0.4750, 0.3924]],

        [[0.5036, 0.1196, 0.9676],
         [0.3249, 0.5679, 0.1693],
         [0.

Zeros and Ones


In [ ]:
#tensor of zeros
zero = torch.zeros(3,4)
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zero*random_ten

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#tensor of ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
random_ten.dtype

torch.float32

### creating range of tensors & tensors alike

In [ ]:
#using torch.range/arange
one_ten = torch.arange(0,10,2)
one_ten

tensor([0, 2, 4, 6, 8])

In [ ]:
#tensor like
ten_zero = torch.zeros_like(one_ten)
ten_zero

tensor([0, 0, 0, 0, 0])

In [ ]:
ten_shape = torch.arange(1,100,5)
#ten_shape
ten1_shape = torch.ones_like(ten_shape)
ten2_shape = torch.zeros_like(ten_shape)
rten = torch.rand(1,20)
ten1_shape + ten2_shape + rten

tensor([[1.4643, 1.2866, 1.8787, 1.2830, 1.2082, 1.3882, 1.5399, 1.0947, 1.9727,
         1.2912, 1.0649, 1.2600, 1.2369, 1.5780, 1.8827, 1.1771, 1.4109, 1.6027,
         1.3848, 1.9000]])

###Tensor datatypes

In [ ]:
#float 32 tensor
f32_ten = torch.tensor([3.0,6.0,9.0], #anything else is auto assigned, no need t add manually.
                       dtype=None,
                       device = None, #dev ur tensor on + track gradient w this op
                       requires_grad = False) #
f32_ten

tensor([3., 6., 9.])

In [ ]:
f32_ten.dtype

torch.float32

### problems with tensors:
1. not right data type => f16 in f32
2. not right shape => matrix mult
3. not right device => device ="cpu" / "cuda" -> operations on tensors on diff devices.

In [ ]:
f16_Ten = f32_ten.type(torch.float16)
f16_Ten #conversion to not run into "not right shape" problem.

tensor([3., 6., 9.], dtype=torch.float16)