In [1]:
import numpy as np
import torch
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.7.1+cpu


#introduction to tensors


In [2]:
#scalar
scalar = torch.tensor(7)
scalar


tensor(7)

pytorch tensors are created using torch.Tensors() => read assignment

In [3]:
scalar.ndim

0

In [4]:
#get tensor back as python int
scalar.item()

7

In [5]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
#matrix
MATRIX = torch.tensor([[2,3],[6,9]])
MATRIX

tensor([[2, 3],
        [6, 9]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
#tensor
TENSOR = torch.tensor([[[[5,5,5],[5,5,5]], [[6,6,5], [6,6,5]], [[1,1,1], [1,1,1]]]])
TENSOR

tensor([[[[5, 5, 5],
          [5, 5, 5]],

         [[6, 6, 5],
          [6, 6, 5]],

         [[1, 1, 1],
          [1, 1, 1]]]])

In [12]:
TENSOR.ndim

4

In [13]:
TENSOR.shape

torch.Size([1, 3, 2, 3])

1 batch, 3 matrices, 2 rows, 3 columns. => 4D tensor.


---



###Random tensor


- why random tensors?
- cus the way many NN kearns => start of tensors of rands, adjust em th represent data

steps?

`start w rand => look @data => update rand => look @data => update rand`

t2: ==> read randoms from documentation>>>

In [14]:
#random tensors => shape (3,4)

random_ten = torch.rand(3,4)
random_ten

tensor([[0.2255, 0.1464, 0.0338, 0.0978],
        [0.6674, 0.2247, 0.9470, 0.3636],
        [0.4787, 0.7990, 0.7042, 0.4242]])

In [15]:
random_ten.ndim

2

In [16]:
ran_ten = torch.rand(10,10)
ran_ten

tensor([[0.1106, 0.8097, 0.9217, 0.1522, 0.4132, 0.2903, 0.8921, 0.1635, 0.5010,
         0.8420],
        [0.8282, 0.9395, 0.4626, 0.9521, 0.7067, 0.4832, 0.0150, 0.0383, 0.8425,
         0.7084],
        [0.2272, 0.4648, 0.7638, 0.0894, 0.6805, 0.5557, 0.3055, 0.6594, 0.5281,
         0.2094],
        [0.5601, 0.9697, 0.6749, 0.0128, 0.3937, 0.4144, 0.0678, 0.3781, 0.0459,
         0.8342],
        [0.6921, 0.0184, 0.3068, 0.9173, 0.0852, 0.6317, 0.9187, 0.1717, 0.8258,
         0.2951],
        [0.5113, 0.6613, 0.6719, 0.3238, 0.0859, 0.5932, 0.8661, 0.8172, 0.4464,
         0.8983],
        [0.6684, 0.6523, 0.2353, 0.6646, 0.7835, 0.7318, 0.1847, 0.1972, 0.3319,
         0.1590],
        [0.4991, 0.8197, 0.3198, 0.8031, 0.1562, 0.9349, 0.3170, 0.1122, 0.4154,
         0.3059],
        [0.9292, 0.1181, 0.6859, 0.1295, 0.8829, 0.6842, 0.8076, 0.3120, 0.6920,
         0.7428],
        [0.3140, 0.1855, 0.8535, 0.8907, 0.1373, 0.8497, 0.4190, 0.3910, 0.1560,
         0.5459]])

In [17]:
ran_ten.ndim

2

In [18]:
ran_tenn = torch.rand(3,3,3)
ran_tenn
ran_tenn.ndim

3

### Random tensor similar shape as image tensor:

In [19]:
rand_img_tens = torch.rand(size=(244,244,3))
#heigt, width, color channel(rgb)
rand_img_tens.shape, rand_img_tens.ndim

(torch.Size([244, 244, 3]), 3)

In [20]:
rand_img_tens

tensor([[[0.3408, 0.6102, 0.7385],
         [0.2711, 0.1030, 0.4830],
         [0.6929, 0.3825, 0.3668],
         ...,
         [0.0215, 0.7615, 0.6095],
         [0.0389, 0.9573, 0.5701],
         [0.3832, 0.0043, 0.8994]],

        [[0.7872, 0.5191, 0.9704],
         [0.6987, 0.6738, 0.8393],
         [0.1391, 0.3846, 0.6023],
         ...,
         [0.0638, 0.8624, 0.9673],
         [0.6226, 0.2244, 0.1426],
         [0.3333, 0.1507, 0.2697]],

        [[0.0430, 0.2493, 0.9715],
         [0.3922, 0.1277, 0.8360],
         [0.0366, 0.9120, 0.0723],
         ...,
         [0.8649, 0.6465, 0.3162],
         [0.0996, 0.7713, 0.8520],
         [0.7525, 0.5496, 0.7135]],

        ...,

        [[0.4035, 0.2465, 0.5332],
         [0.6675, 0.4931, 0.6609],
         [0.7659, 0.1547, 0.0433],
         ...,
         [0.6417, 0.2536, 0.4550],
         [0.6372, 0.8863, 0.5355],
         [0.7308, 0.9176, 0.5187]],

        [[0.2652, 0.0173, 0.2980],
         [0.6858, 0.6755, 0.7390],
         [0.

Zeros and Ones


In [21]:
#tensor of zeros
zero = torch.zeros(3,4)
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
zero * random_ten

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
#tensor of ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [24]:
ones.dtype

torch.float32

In [25]:
random_ten.dtype

torch.float32

### creating range of tensors & tensors alike

In [26]:
#using torch.range/arange
one_ten = torch.arange(0,10,2)
one_ten

tensor([0, 2, 4, 6, 8])

In [27]:
#tensor like
ten_zero = torch.zeros_like(one_ten)
ten_zero

tensor([0, 0, 0, 0, 0])

In [28]:
ten_shape = torch.arange(1,100,5)
#ten_shape
ten1_shape = torch.ones_like(ten_shape)
ten2_shape = torch.zeros_like(ten_shape)
rten = torch.rand(1,20)
ten1_shape + ten2_shape + rten

tensor([[1.4542, 1.5236, 1.3842, 1.7644, 1.5104, 1.4890, 1.9586, 1.6332, 1.8569,
         1.6494, 1.9922, 1.9208, 1.2422, 1.1000, 1.2020, 1.6188, 1.0017, 1.5927,
         1.8671, 1.4946]])

###Tensor datatypes

In [29]:
#float 32 tensor
f32_ten = torch.tensor([3.0,6.0,9.0], #anything else is auto assigned, no need t add manually.
                       dtype=None,
                       device = None, #dev ur tensor on + track gradient w this op
                       requires_grad = False) #
f32_ten

tensor([3., 6., 9.])

In [30]:
f32_ten.dtype

torch.float32

### problems with tensors:
1. not right data type => f16 in f32
2. not right shape => matrix mult
3. not right device => device ="cpu" / "cuda" -> operations on tensors on diff devices.

In [31]:
f16_Ten = f32_ten.type(torch.float16)
f16_Ten #conversion to not run into "not right shape" problem.

tensor([3., 6., 9.], dtype=torch.float16)

In [32]:
f16_Ten * f32_ten

tensor([ 9., 36., 81.])

In [33]:
int32 = torch.tensor([3,6,9], dtype = torch.int32)
int32


tensor([3, 6, 9], dtype=torch.int32)

In [34]:
int32 * f16_Ten

tensor([ 9., 36., 81.], dtype=torch.float16)

### getting info from tensors

- data type check => to get data type: use tensor.dtype
- shape check => tensor.shape
- device => tensor.device


In [35]:
some = torch.rand(3,4)
some

tensor([[0.7871, 0.6522, 0.3016, 0.7262],
        [0.9799, 0.0119, 0.0334, 0.9019],
        [0.5987, 0.0328, 0.8499, 0.9484]])

In [36]:
#fetch details
print(some)
print(f"data type: {some.dtype}")
print(some.size())
print(some.shape)
print(some.device)
some = some.to('cpu')
print(some.device)


tensor([[0.7871, 0.6522, 0.3016, 0.7262],
        [0.9799, 0.0119, 0.0334, 0.9019],
        [0.5987, 0.0328, 0.8499, 0.9484]])
data type: torch.float32
torch.Size([3, 4])
torch.Size([3, 4])
cpu
cpu


### manipulating tensors
- addition
- subtraction
* multiplication
- division
- MATRIX MULTIP

In [37]:
# addition
tensor = torch.tensor([1,2,3])
#tensor + 10
#tensor *10
#tensor -10
#tensor/10


In [38]:
#there's built-in functions:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [39]:
#MATRIX MUL
#1. element wiste
print(tensor * tensor)


tensor([1, 4, 9])


In [40]:
#2. dot product
%time

torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 26 μs


tensor(14)

In [41]:
#MATRIX MUL by hand
#1*1 + 2*2 + 3*3

%time
sum =0
for i in tensor:
  sum += i*i

sum

CPU times: total: 0 ns
Wall time: 21.2 μs


tensor(14)

### one of the most common errors in matrix multiplication => shape error
-- inner dimensions MUST match

In [ ]:
# shapes for mat mul
tensor_a = torch.tensor([[1,2], [3,4],[5,6]])
tensor_b = torch.tensor([[1,2], [3,4],[5,6]])

#torch.mm(tensor_a, tensor_b) #alias for matmul
#RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

### to fix the shape issues => **transpose**
transpose -> switches axes or dimensions of a given tensor


In [43]:
tensor_b.T, tensor_b.T.shape
#makes a copy, doesn't change the original tensor_b

(tensor([[1, 3, 5],
         [2, 4, 6]]),
 torch.Size([2, 3]))

In [44]:
#works when b is transposed
torch.mm(tensor_a, tensor_b.T)

tensor([[ 5, 11, 17],
        [11, 25, 39],
        [17, 39, 61]])

## Tensor aggregation


In [45]:
x = torch.arange(1,100,10)
x


tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [46]:
torch.min(x) , x.min()

(tensor(1), tensor(1))

In [47]:
torch.max(x),  x.max()

(tensor(91), tensor(91))

In [48]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()
#RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long
#tensor NOT THE RIGHT DATA TYPE ==> HIDDEN

(tensor(46.), tensor(46.))

In [49]:
x.dtype
#long = int

torch.int64

In [50]:
torch.sum(x), x.sum()

(tensor(460), tensor(460))

### positional min, max?
- finding the position in tensor that has the min val with argmin, returns index position of target tensor when min val occures


In [51]:
x.argmin() #for the min val's INDEX VALUE

tensor(0)

In [52]:
x[0]

tensor(1)

In [53]:
x.argmax()

tensor(9)

In [54]:
x[9]

tensor(91)

## reshaping, stacking, squeezing, unsqueezing

- reshaping: -shape mismatch in MATRIX- => reshapes tensor in defined shape
- view: return view of a tensor in some shape, but just a copy not the original one
- stacking: combine multi tensors on top -vstack- or side by side -hstack- 