<a href="https://colab.research.google.com/github/0xmennatullah/PyTorch/blob/main/colab_code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import torch
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.7.1+cpu


#introduction to tensors


In [ ]:
#scalar
scalar = torch.tensor(7)
scalar


tensor(7)

pytorch tensors are created using torch.Tensors() => read assignment

In [ ]:
scalar.ndim

0

In [ ]:
#get tensor back as python int
scalar.item()

7

In [ ]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#matrix
MATRIX = torch.tensor([[2,3],[6,9]])
MATRIX

tensor([[2, 3],
        [6, 9]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#tensor
TENSOR = torch.tensor([[[[5,5,5],[5,5,5]], [[6,6,5], [6,6,5]], [[1,1,1], [1,1,1]]]])
TENSOR

tensor([[[[5, 5, 5],
          [5, 5, 5]],

         [[6, 6, 5],
          [6, 6, 5]],

         [[1, 1, 1],
          [1, 1, 1]]]])

In [ ]:
TENSOR.ndim

4

In [ ]:
TENSOR.shape

torch.Size([1, 3, 2, 3])

1 batch, 3 matrices, 2 rows, 3 columns. => 4D tensor.


---



###Random tensor


- why random tensors?
- cus the way many NN kearns => start of tensors of rands, adjust em th represent data

steps?

`start w rand => look @data => update rand => look @data => update rand`

t2: ==> read randoms from documentation>>>

In [ ]:
#random tensors => shape (3,4)

random_ten = torch.rand(3,4)
random_ten

tensor([[0.1013, 0.6285, 0.7975, 0.8212],
        [0.4751, 0.8528, 0.7007, 0.3926],
        [0.4635, 0.7436, 0.2341, 0.6906]])

In [ ]:
random_ten.ndim

2

In [ ]:
ran_ten = torch.rand(10,10)
ran_ten

tensor([[0.2831, 0.0975, 0.5050, 0.0110, 0.4011, 0.8133, 0.4288, 0.8804, 0.5896,
         0.0980],
        [0.7246, 0.6202, 0.2194, 0.2008, 0.4975, 0.3952, 0.2849, 0.5724, 0.6095,
         0.6831],
        [0.2567, 0.0709, 0.9081, 0.7624, 0.8887, 0.4980, 0.7016, 0.9556, 0.6208,
         0.3079],
        [0.6958, 0.9546, 0.0659, 0.4097, 0.2161, 0.7250, 0.0097, 0.1136, 0.9478,
         0.4612],
        [0.1145, 0.9804, 0.8941, 0.4239, 0.1046, 0.2279, 0.0319, 0.5436, 0.8912,
         0.0760],
        [0.6255, 0.6909, 0.8832, 0.3375, 0.4189, 0.6910, 0.9056, 0.2716, 0.0437,
         0.5008],
        [0.3171, 0.4473, 0.0549, 0.4194, 0.8501, 0.8332, 0.4794, 0.7314, 0.8226,
         0.9696],
        [0.8410, 0.6544, 0.9572, 0.1206, 0.4187, 0.3479, 0.3034, 0.7894, 0.4243,
         0.3784],
        [0.8500, 0.4645, 0.8271, 0.9427, 0.8099, 0.7366, 0.5402, 0.5497, 0.0387,
         0.3424],
        [0.2585, 0.5020, 0.1981, 0.2222, 0.2236, 0.6599, 0.2038, 0.1401, 0.4160,
         0.7690]])

In [ ]:
ran_ten.ndim

2

In [ ]:
ran_tenn = torch.rand(3,3,3)
ran_tenn
ran_tenn.ndim

3

### Random tensor similar shape as image tensor:

In [ ]:
rand_img_tens = torch.rand(size=(244,244,3))
#heigt, width, color channel(rgb)
rand_img_tens.shape, rand_img_tens.ndim

(torch.Size([244, 244, 3]), 3)

In [ ]:
rand_img_tens

tensor([[[8.7816e-01, 8.3910e-01, 6.7955e-01],
         [7.2536e-01, 9.3893e-02, 8.6912e-02],
         [3.0037e-01, 2.1690e-01, 6.4866e-01],
         ...,
         [7.6079e-01, 2.8956e-01, 4.8806e-01],
         [5.8589e-01, 5.7491e-01, 8.2580e-01],
         [5.3368e-01, 2.5497e-02, 8.7491e-01]],

        [[6.3283e-01, 1.6517e-01, 2.3855e-01],
         [7.6873e-01, 3.2895e-01, 7.7051e-01],
         [8.6380e-01, 2.8469e-01, 2.2785e-01],
         ...,
         [6.9485e-01, 4.7462e-01, 2.5957e-01],
         [7.9263e-01, 5.8846e-01, 3.1318e-01],
         [5.7586e-01, 2.5265e-03, 5.8351e-01]],

        [[4.3373e-01, 4.1546e-01, 4.1786e-01],
         [2.5562e-01, 9.9117e-01, 2.1325e-01],
         [1.2225e-01, 6.6443e-01, 3.2832e-01],
         ...,
         [9.1377e-01, 1.1678e-01, 2.5024e-01],
         [7.5759e-01, 4.5590e-01, 5.2340e-01],
         [4.8469e-01, 3.1241e-01, 4.6486e-01]],

        ...,

        [[2.2992e-01, 8.2883e-01, 6.1026e-01],
         [5.4318e-01, 2.8607e-01, 9.1523e-01]

Zeros and Ones


In [ ]:
#tensor of zeros
zero = torch.zeros(3,4)
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zero * random_ten

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#tensor of ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
random_ten.dtype

torch.float32

### creating range of tensors & tensors alike

In [ ]:
#using torch.range/arange
one_ten = torch.arange(0,10,2)
one_ten

tensor([0, 2, 4, 6, 8])

In [ ]:
#tensor like
ten_zero = torch.zeros_like(one_ten)
ten_zero

tensor([0, 0, 0, 0, 0])

In [ ]:
ten_shape = torch.arange(1,100,5)
#ten_shape
ten1_shape = torch.ones_like(ten_shape)
ten2_shape = torch.zeros_like(ten_shape)
rten = torch.rand(1,20)
ten1_shape + ten2_shape + rten

tensor([[1.1692, 1.6618, 1.2185, 1.0081, 1.7013, 1.2714, 1.4934, 1.0463, 1.7912,
         1.6556, 1.3259, 1.2182, 1.6459, 1.1502, 1.7720, 1.4926, 1.5718, 1.7391,
         1.1157, 1.0932]])

###Tensor datatypes

In [ ]:
#float 32 tensor
f32_ten = torch.tensor([3.0,6.0,9.0], #anything else is auto assigned, no need t add manually.
                       dtype=None,
                       device = None, #dev ur tensor on + track gradient w this op
                       requires_grad = False) #
f32_ten

tensor([3., 6., 9.])

In [ ]:
f32_ten.dtype

torch.float32

### problems with tensors:
1. not right data type => f16 in f32
2. not right shape => matrix mult
3. not right device => device ="cpu" / "cuda" -> operations on tensors on diff devices.

In [ ]:
f16_Ten = f32_ten.type(torch.float16)
f16_Ten #conversion to not run into "not right shape" problem.

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
f16_Ten * f32_ten

tensor([ 9., 36., 81.])

In [ ]:
int32 = torch.tensor([3,6,9], dtype = torch.int32)
int32


tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
int32 * f16_Ten

tensor([ 9., 36., 81.], dtype=torch.float16)

### getting info from tensors

- data type check => to get data type: use tensor.dtype
- shape check => tensor.shape
- device => tensor.device


In [ ]:
some = torch.rand(3,4)
some

tensor([[0.0177, 0.2061, 0.6062, 0.1163],
        [0.0474, 0.4771, 0.0206, 0.7774],
        [0.6899, 0.1488, 0.3387, 0.5676]])

In [ ]:
#fetch details
print(some)
print(f"data type: {some.dtype}")
print(some.size())
print(some.shape)
print(some.device)
some = some.to('cpu')
print(some.device)


tensor([[0.0177, 0.2061, 0.6062, 0.1163],
        [0.0474, 0.4771, 0.0206, 0.7774],
        [0.6899, 0.1488, 0.3387, 0.5676]])
data type: torch.float32
torch.Size([3, 4])
torch.Size([3, 4])
cpu
cpu


### manipulating tensors
- addition
- subtraction
* multiplication
- division
- MATRIX MULTIP

In [ ]:
# addition
tensor = torch.tensor([1,2,3])
#tensor + 10
#tensor *10
#tensor -10
#tensor/10


In [ ]:
#there's built-in functions:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
#MATRIX MUL
#1. element wiste
print(tensor * tensor)


tensor([1, 4, 9])


In [ ]:
#2. dot product
%time

torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 26.2 μs


tensor(14)

In [ ]:
#MATRIX MUL by hand
#1*1 + 2*2 + 3*3

%time
sum =0
for i in tensor:
  sum += i*i

sum

CPU times: total: 0 ns
Wall time: 26.5 μs


tensor(14)

### one of the most common errors in matrix multiplication => shape error
-- inner dimensions MUST match

In [ ]:
# shapes for mat mul
tensor_a = torch.tensor([[1,2], [3,4],[5,6]])
tensor_b = torch.tensor([[1,2], [3,4],[5,6]])

#torch.mm(tensor_a, tensor_b) #alias for matmul
#RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

### to fix the shape issues => **transpose**
transpose -> switches axes or dimensions of a given tensor


In [ ]:
tensor_b.T, tensor_b.T.shape
#makes a copy, doesn't change the original tensor_b

(tensor([[1, 3, 5],
         [2, 4, 6]]),
 torch.Size([2, 3]))

In [ ]:
#works when b is transposed
torch.mm(tensor_a, tensor_b.T)

tensor([[ 5, 11, 17],
        [11, 25, 39],
        [17, 39, 61]])

## Tensor aggregation


In [ ]:
x = torch.arange(1,100,10)
x


tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
torch.min(x) , x.min()

(tensor(1), tensor(1))

In [ ]:
torch.max(x),  x.max()

(tensor(91), tensor(91))

In [ ]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()
#RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long
#tensor NOT THE RIGHT DATA TYPE ==> HIDDEN

(tensor(46.), tensor(46.))

In [ ]:
x.dtype
#long = int

torch.int64

In [ ]:
torch.sum(x), x.sum()

(tensor(460), tensor(460))

### positional min, max?
- finding the position in tensor that has the min val with argmin, returns index position of target tensor when min val occures


In [ ]:
x.argmin() #for the min val's INDEX VALUE

tensor(0)

In [ ]:
x[0]

tensor(1)

In [ ]:
x.argmax()

tensor(9)

In [ ]:
x[9]

tensor(91)

## reshaping, stacking, squeezing, unsqueezing

- reshaping: -shape mismatch in MATRIX- => reshapes tensor in defined shape
- view: return view of a tensor in some shape, but just a copy not the original one
- stacking: combine multi tensors on top -vstack- or side by side -hstack-
- squeeze: removes all `1` dimensions from tensor
- unsqueeze: adds `1` dimension to a target tensor
- permute: return view of input with dimensions (swapped) in a certain way

In [ ]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
#reshape: extra dim => gotta be compatible with original size
x_reshaped = x.reshape(1,9)
#(2,9) => 18 elements, 9/dim
#(9,1) => 1 element, 9 dim
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
#view => shares memo with ORIGINAL tensor
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
#changing z => changes x
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
#stack => v:0, h:1
x_stack = torch.stack([x,x,x,x], dim=0)
x_stack

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
#squeeze
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_squeezed = x_reshaped.squeeze()
x_squeezed
#shape=[9] => removes all 1 dimensions!

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
#unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=1) #dim=0 aka adding the extra dimension to the zeroth index of the size/tensor or adding new dimension in new index => dim=1
x_unsqueezed

tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [ ]:
#permute => rearrange dim of target tensor in specified order
#try image example:
x_original = torch.rand(size =(244,244,3) )

#return view(shares original memo) => view that changes the SIZE DIM themselves
x_perm = x_original.permute(2,0,1)

print(f"prev shape: {x_original.shape}")
print(f"new shape: {x_perm.shape}")
#same data, different POV, share same memory even though diff shapes

prev shape: torch.Size([244, 244, 3])
new shape: torch.Size([3, 244, 244])


## indexing

In [ ]:
import torch
x = torch.arange(1, 10).reshape(1,3,3) #9 values, 1 dim, 3 in each 3
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
#indexes the first outer bracket/dimension
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
#index the inner bracket/dimension=1
x[0][0]

tensor([1, 2, 3])

In [ ]:
#index most inner bracket dim=2
x[0][0][0]

tensor(1)

In [ ]:
#index with range ":"
#get all 0th, 1st dim elements, but only the 1st or 2nd element of the 2nd dim
x[:,:,1] #vertical line, 2nd column

tensor([[2, 5, 8]])

In [ ]:
#all values of 0th dim, only 2nd index from the 1st, 2nd dimensions
# aka 1st row, 1st element => dim here are index, row, col.
x[:, 1,1]

tensor([5])

In [ ]:
x[0,0,:]

tensor([1, 2, 3])

In [ ]:
x[0, 2, 2] #last element of the last row of the last dim

tensor(9)

In [ ]:
x[0, :, 2]

tensor([3, 6, 9])

In [ ]:
x = torch.arange(1,10)
x.shape, x

(torch.Size([9]), tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]))

## NUMPY
scientific numerical computing lib.
- data in numpy, want in pytorch tensor `torch.from_numpy(ndarray)`
- pytorch tensor to numpy `torch.Tensor.numpy()`

In [ ]:
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) #gets u new tensor in memory
array, tensor
#converting from np -> pytorch ==> reflecting numpy's default datatype float64
#pytorch default is float32, so we need to convert it
##### might run into dt issues in calc with float64


(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
#change array, change tensor?
array = array+1
array, tensor

(array([3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
#tensor to numpy array
tensor = torch.ones(7)
np_tensor = tensor.numpy()
tensor, np_tensor
#here gets the default of the tensor -> float32, so the numpy array is float32 as well
#numpy array is float64 by default, so we need to convert it

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
#changing tensor, changes arra? => no, don't share memory
tensor = tensor+1
tensor, np_tensor

(tensor([3., 3., 3., 3., 3., 3., 3.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## reproducabitlity => taking random outta random
how nn learns:
 - start with random numbers
 - perform tensor op
 - update random numbers
 - make better representation of the data
 - again, again, again

to reduce randomness => **random seed**

what random seed does? => flavour randomness
=> pc is deterministic most of the time

further search == psudo randomness, reducability

In [ ]:
rand_a = torch.rand(5,5)
rand_b = torch.rand(5,5)

print(rand_a)
print(rand_b)
print(rand_a == rand_b)

tensor([[0.8663, 0.0771, 0.1402, 0.8742, 0.5955],
        [0.1204, 0.9312, 0.4532, 0.3918, 0.9689],
        [0.7622, 0.1799, 0.9326, 0.9994, 0.7382],
        [0.7422, 0.9139, 0.2864, 0.6953, 0.4722],
        [0.1277, 0.9005, 0.5793, 0.4165, 0.3061]])
tensor([[0.9759, 0.8161, 0.8603, 0.9719, 0.8566],
        [0.0021, 0.8123, 0.1969, 0.6361, 0.3716],
        [0.4937, 0.8734, 0.0478, 0.7698, 0.9310],
        [0.0635, 0.1328, 0.6881, 0.4421, 0.3827],
        [0.6671, 0.4095, 0.1492, 0.3477, 0.0391]])
tensor([[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]])


In [ ]:
import torch

## random reproducable tensors



In [ ]:
#set random seed
random_seed = 55
torch.manual_seed(random_seed)

rand_tensor = torch.rand(3,4)

torch.manual_seed(random_seed)
rand_tensor2 = torch.rand(3,4)

rand_tensor, rand_tensor2, rand_tensor == rand_tensor2

(tensor([[0.8357, 0.9378, 0.7439, 0.5674],
         [0.8682, 0.4765, 0.0858, 0.7740],
         [0.9677, 0.1874, 0.0993, 0.0611]]),
 tensor([[0.8357, 0.9378, 0.7439, 0.5674],
         [0.8682, 0.4765, 0.0858, 0.7740],
         [0.9677, 0.1874, 0.0993, 0.0611]]),
 tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]))

## tensors and pytorch objeects on GPUs (making faster computations)
